name: build_push_pr_ecr

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ dev ]

jobs:
  build_push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Lint shell scripts
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - run: echo ::set-env name=pull_number::$(jq — raw-output .pull_request.number $GITHUB_EVENT_PATH)

      - name: Build image
        run: docker build . --tag hls-sentinel

      - name: Push to latest ECR
        id: push-latest-ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-west-2
          local-image: hls-sentinel
          image: hls-sentinel:${pull_number}
